# Basics of python and numpy

Outline

- Import statements
- Printing
- Variables and types
- Basic arithmetic
- NumPy Arrays: Vectors
- Numpy Arrays: Matrices
- Dot products between vectors
- Matrix-vector products
- Matrix-matrix products
- Hermitian matrices
- Eigenvalues and eigenvectors
- Commutators


## Import statements
Python has intrinsic functionality as a programming language, but there are also many special-purpose libraries that are helpful.  Here we will use the library `numpy` for numerical computing.

In [40]:
import numpy as np
from numpy import linalg as la

## Printing
The way to communicate between the computer and you is through different types of print statements.  These can display data to the screen, or write data to a file.  We can also plot data, which we will see in a future lesson.  For now, we will use the print statement to write the canonical first program: Hello World

In [41]:
print("Hello World!")

Hello World!


## Variables and types
Much of the power of programming languages lies in the ability to perform complicated operators on data.  Data used throughout a program is stored in variables.  We can use *most* any name we want for variables, though there are some best practices:  we should try to use descriptive names when possible, we should use lower case letters, we should separate words in compound names with an underscore.  We **cannot** use certain words that correspond to built-in functions in python, like `print`, `for`, `while`, `if`, `elif`, `else`, `type` to name a few commmon ones. 

We can also store many types of data as variables.  Data types in python include `int` (integers), `floats` (numbers with decimal places), `str` (strings of characters, e.g. words), `complex` (complex numbers), `bool` (boolean True/False). 

In [42]:
# the following variable is a string
my_message = "Hello World!"

# thie following variable is an int
my_integer = 1

# the following variable is a float
my_float = 2.1223

print(my_message)

print(my_integer)

print(my_float)

Hello World!
1
2.1223


## Basic Arithmetic
We can perform addition, substraction, division, and multiplication using the 
`+`, `-`, `/`, `*` operators.  Try using these operations with the variables that are pre-defined for you below

In [43]:
my_float_1 = 3.12
my_float_2 = 2.11

my_int_1 = 2
my_int_2 = 5

my_string_1 = "string 1"
my_string_2 = "string 2"

my_float_3 = my_float_1 + my_float_2
print(my_float_3)

my_string_3 = my_string_1 + my_string_2
print(my_string_3)

5.23
string 1string 2


## Numpy arrays: Vectors
Numpy arrays are special types of variables that can make use of different mathematical operation in the numpy library.  We will see that a lot of linear algebra operations can be performed with numpy arrays using very simple syntax.  Numpy arrays can have an arbitrary number of dimensions, but we will use 2-dimensional numpy arrays with 
a single column and multiple rows to denote a column vector.  We can take the transpose of these numpy arrays to represent a row vector.  

Let's use as an example the basis states of spin kets that we have seen / will see soon in lecture:

\begin{equation}
|\chi_{\alpha}^{(z)} \rangle= 
\begin{bmatrix}
  1 \\
  0 \\
\end{bmatrix}
\end{equation}


\begin{equation}
|\chi_{\beta}^{(z)}\rangle = 
\begin{bmatrix}
  0 \\
  1 \\
\end{bmatrix}
\end{equation}

$|\chi_{\alpha}^{(z)}$ can be formed using the following syntax:
`ket_alpha = np.array([[1],[0]])`

We can get the number of rows and number of columns (the shape) of this vector using `np.shape(ket_alpha)`.

In [44]:
# insert code to assign ket chi_alpha
ket_alpha = np.array([[1],[0]])

# insert code to assign ket chi_beta
ket_beta = np.array([[0],[1]])

# insert code to print both kets
print("|Chi_alpha>")
print(ket_alpha)

print("|Chi_beta>")
print(ket_beta)

# compute and print the shape of bra_alpha
print(np.shape(ket_alpha))

|Chi_alpha>
[[1]
 [0]]
|Chi_beta>
[[0]
 [1]]
(2, 1)


We can form the bras corresponding to these kets by taking the complex conjugate and transpose of the column vectors we have just formed.  The result will be row vectors, keeping the correspondence to the "bra" - "ket" convention.

$$ \langle \chi_{\alpha}^{(z)}| = |\chi_{\alpha}^{(z)}\rangle ^{\dagger} = [1^* \: 0^*] $$

$$ \langle \chi_{\beta}^{(z)}| = |\chi_{\beta}^{(z)}\rangle ^{\dagger} = [0^* \: 1^*]$$

This operation can be computed using the following syntax:
`bra_alpha = ket_alpha.conj().T`

You can compute the shape of the bras in the same way as you used for the kets; take note of how the shape changes.

In [45]:
# insert code to assign bra chi_alpha as adjoint of ket chi_alpha
bra_alpha = ket_alpha.conj().T

# insert code to assign bra chi_beta as adjoint of ket chi_beta
bra_beta = ket_beta.conj().T

# insert code to print both bras
print("<Chi_alpha|")
print(bra_alpha)

print("<Chi_beta|")
print(bra_beta)

# compute and print the shape of bra_alpha
print(np.shape(bra_alpha))

<Chi_alpha|
[[1 0]]
<Chi_beta|
[[0 1]]
(1, 2)


## Computing the bra-ket
We can view the bra-ket (also called the inner product between the bra and the ket) as a test of how much the state in the bra projects on to the state in the ket.  The answer can be anywhere between 0 (the states do not project onto each other at all, they are orthogonal states, they do not overlap at all) to 1 (these states perfectly project onto one another, they have perfect overlap, they are identical states).  We know (or will soon learn) that the spin states are orthonormal states: they have perfect overlap with themselves and zero overlap with each other.  This is codified with the following mathematical statements

$$\langle \chi_n^{(z)} | \chi_m^{(z)}\rangle = \delta_{nm} $$

where where have used the Kronecker delta function $\delta_{nm} = 0$ if $n\neq m$ and $\delta_{nm} = 1$ if $n=m$.

With their vector representations, we can compute the bra-ket using the dot product as follows:
`bra_ket_aa = np.dot(bra_alpha, ket_alpha)`


In [46]:
# insert code to compute <alpha|alpha>
bra_ket_aa = np.dot(bra_alpha, ket_alpha)

# insert code to compute <alpha|beta>
bra_ket_ab = np.dot(bra_alpha, ket_beta)

# insert code to compute <beta|alpha>
bra_ket_ba = np.dot(bra_beta, ket_alpha)

# insert code to compute <beta|beta>
bra_ket_bb = np.dot(bra_beta, ket_beta)

# print all bra-kets to make sure they behave as expected
print("<alpha|alpha> = ", bra_ket_aa)
print("<alpha|beta> = ", bra_ket_ab)
print("<beta|alpha> = ", bra_ket_ba)
print("<beta|beta> = ", bra_ket_bb)

<alpha|alpha> =  [[1]]
<alpha|beta> =  [[0]]
<beta|alpha> =  [[0]]
<beta|beta> =  [[1]]


## Numpy arrays: Matrices
We will use 2-dimensional numpy arrays with 
a an equal number of rows and columns to denote square matrices.  
Let's use as an example matrix representation of the $\hat{S}_z$ operator that we have seen / will see soon in lecture:

\begin{equation}
\mathbb{S}_z = \frac{\hbar}{2}
\begin{bmatrix}
  1 & 0 \\
  0 & -1 \\
\end{bmatrix}
\end{equation}


$\mathbb{S}_z$ can be formed using the following syntax:
`Sz = hbar / 2 * np.array([[1, 0],[0, -1]])`

You can take the shape of the Sz matrix as before; take note of how its shape compares to the shape of the bras and kets.

**Note** The value of $\hbar$ in atomic units is 1.

In [47]:
# define hbar in atomic units
hbar = 1

# insert code to define the Sz matrix
Sz = hbar / 2 * np.array([[1, 0],[0, -1]])

# insert code to print the matrix
print(Sz)

# print shape of Sz
print(np.shape(Sz))

[[ 0.5  0. ]
 [ 0.  -0.5]]
(2, 2)


## Matrix-vector products
An important property of the basis kets $|\chi_{\alpha}^{(z)} \rangle$ and $|\chi_{\beta}^{(z)} \rangle$ is that they were eigenstates of the $\hat{S}_z$ operator satisfying

$$ \hat{S}_z |\chi_{\alpha}^{(z)} \rangle = +\frac{\hbar}{2}|\chi_{\alpha}^{(z)} \rangle $$

$$ \hat{S}_z |\chi_{\beta}^{(z)} \rangle = -\frac{\hbar}{2}|\chi_{\beta}^{(z)} \rangle $$.

This property should be preserved with the matrix and vector representations of these operators and states, respectively.  We can confirm this by taking the matrix-vector product between $\mathbb{S}_z$ and the vectors corresponding to these basis kets using the syntax

`Sz_ket_a = np.dot(Sz, ket_alpha)`


We can inspect them to see if this relationship holds, but see if you can figure an alternative way to confirm the relationship holds.

In [48]:
# compute product of Sz and ket_alpha
Sz_ket_a = np.dot(Sz, ket_alpha)

# compute product of Sz and ket_beta
Sz_ket_b = np.dot(Sz, ket_beta)

# print product of Sz and ket_alpha
print(Sz_ket_a)

# print product of Sz and ket_beta
print(Sz_ket_b)

[[0.5]
 [0. ]]
[[ 0. ]
 [-0.5]]


## Hermitian matrices 
The matrix representations of operators in quantum mechanics are called Hermitian matrices.  Hermitian matrices have the special relationship that they are equal to their adjoint (i.e., their complex conjugate transpose).  

You can confirm that $\mathbb{S}_z$ is Hermitian by the following syntax:

`Sz_adjoint = Sz.conj().T`
`print(np.allclose(Sz_adjoint, Sz))`

where the first line computes the adjoint of $\mathbb{S}_z$ and stores it to a variable `Sz_adjoint` and 
the second line prints the result of comparing all elements of `Sz_adjoint` to `Sz`.  The return value of `True` will
indicate that `Sz_adjoint` is numerically equal to `Sz`.

In [49]:
# Confirm Sz is Hermitian here
Sz_adjoint = Sz.conj().T 
print(np.allclose(Sz_adjoint, Sz))

True


## Eigenvalues and eigenvectors
An important property of Hermitian matrices is that their eigevalues are real numbers.  In quantum mechanics, we associate the possible outcomes of measurements with the eigenvalues of Hermitian operators corresponding to the observable being measured.  In this notebook, we have been talking about the observable of spin angular momentum, which is a vector quantity. We have been specifically looking at the operators and eigenstates related to the z-component of spin angular momentum, denoted $S_z$. We have seen that this operator has two eigenstates, 
$|\chi_{\alpha}^{(z)}\rangle$ and $|\chi_{\beta}^{(z)}\rangle$ with associated eigenvalues $\frac{\hbar}{2}$ and $-\frac{\hbar}{2}$, which are both real numbers.  

These relationships are preserved when we use the matrix - vector representation of operators and eigenstates.  In general, an eigenvalue equation with matrices and vectors satisfies

$$ \mathbb{M} \bf{x} = \lambda \bf{x} $$

where $\lambda$ is an eigenvalue (which is a number) and $\bf{x}$ is an eigenvector.  One way of interpreting these equations is to say that the action of a matrix on its eigenvectors is simply to scale the magnitude of the vector by a number (specifically, scale it by its eigenvalue).  This is a very special situation, because typically speaking, when a vector is multiplied by a matrix, the result is a new vector that points along a new direction and has a different magnitude.  For a lovely explanation with graphical illustrations, please consult [this vide](https://youtu.be/PFDu9oVAE-g).  In fact, the entire 3b1b series on linear algebra is wonderful!

We have already seen that vectors associated with the basis kets $|\chi_{\alpha}^{(z)}\rangle$ and $|\chi_{\beta}^{(z)}\rangle$ obey this relationship with $\mathbb{S}_z$.  What we will now do, is consider the matrices associated with the spin angular momentum components along $x$ and $y$.  We will first see that the 
basis kets $|\chi_{\alpha}^{(z)}\rangle$ and $|\chi_{\beta}^{(z)}\rangle$ are not eigenvectors of $\mathbb{S}_x$ and $\mathbb{S}_y$.  We will then use numpy's linear algebra sub-library to compute the eigenvalues and eigenvectors of these matrices, which will turn out to be linear combinations of $|\chi_{\alpha}^{(z)}\rangle$ and $|\chi_{\beta}^{(z)}\rangle$.  

### Build matrix form of $\mathbb{S}_x$ and $\mathbb{S}_y$
The operator $\hat{S}_x$ has the matrix form
\begin{equation}
\mathbb{S}_x = \frac{\hbar}{2}
\begin{bmatrix}
  0 & 1 \\
  1 & 0 \\
\end{bmatrix}
\end{equation}
and the operator $\hat{S}_y$ has the matrix form
\begin{equation}
\mathbb{S}_y = \frac{\hbar}{2}
\begin{bmatrix}
  0 & -i \\
  i & 0 \\
\end{bmatrix}.
\end{equation}

**Hint** The imaginary unit $i = \sqrt{-1}$ can be accessed as `1j` in python.

In [50]:
# insert code to build Sx
Sx = hbar/2 * np.array([[0, 1], [1, 0]])

# insert code to build Sy
Sy = hbar/2 * np.array([[0, -1j], [1j, 0]])

# print Sx
print(Sx)

# print Sy
print(Sy)

[[0.  0.5]
 [0.5 0. ]]
[[0.+0.j  0.-0.5j]
 [0.+0.5j 0.+0.j ]]


### Take matrix-vector product of $\mathbb{S}_x$ and $\mathbb{S}_y$ with the basis kets
Just as we did with $\mathbb{S}_z$, take the following matrix-vector products:
$$ \mathbb{S}_x |\chi_{\alpha}^{(z)}\rangle $$
$$ \mathbb{S}_x |\chi_{\beta}^{(z)}\rangle $$
$$ \mathbb{S}_y |\chi_{\alpha}^{(z)}\rangle $$
$$ \mathbb{S}_y |\chi_{\beta}^{(z)}\rangle $$

**Question 1:** After inspecting the results of each matrix-vector product, do you think the basis kets are eigenstates of 
$\mathbb{S}_x$ and $\mathbb{S}_y$?  Explain your reasoning.

**Question 2:** What is the shape of the result of each matrix-vector product?


In [51]:
# compute product of Sx and ket_alpha and store to Sx_ket_a; print it
Sx_ket_a = np.dot(Sx, ket_alpha)
print(Sx_ket_a)

# compute product of Sx and ket_beta and store to Sx_ket_b; print it
Sx_ket_b = np.dot(Sx, ket_beta)
print(Sx_ket_b)

# compute product of Sy and ket_beta and store to Sy_ket_b; print it
Sy_ket_a = np.dot(Sy, ket_alpha)
print(Sy_ket_a)

# compute product of Sy and ket_alpha and store to Sy_ket_b; print it
Sy_ket_b = np.dot(Sy, ket_beta)
print(Sy_ket_b)



[[0. ]
 [0.5]]
[[0.5]
 [0. ]]
[[0.+0.j ]
 [0.+0.5j]]
[[0.-0.5j]
 [0.+0.j ]]


### Use `eigh()` to compute the eigenvectors and eigenvalues of $\mathbb{S}_x$ and $\mathbb{S}_y$
Numpy has a linear algebra library that can compute eigenvalues and eigenvectors of Hermitian matrices that is called using the syntax

`eigenvalues, eigenvectors = la.eigh(M)`

where `eigenvalues` will store all of the eigenvectors and `eigenvectors` will store all the eigenvectors.  
Use this method to compute the eigenvalues and eigenvectors of $\mathbb{S}_x$ and $\mathbb{S}_y$.

**Note** A namedtuple with the following attributes:
eigenvectors[:, i] is the normalized eigenvector corresponding to the eigenvalue eigenvalues[i].


**Question 3:** What is the shape of the vals_x?  What is the shape of vecs_x?

**Question 4:** Do these matrices have the same eigenvalues as $\mathbb{S}_z$?  Do they have the same eigenvectors as $\mathbb{S}_z$?

In [52]:
# compute eigenvectors and eigenvalues of Sx, store them to vals_x, vecs_x
vals_x, vecs_x = la.eigh(Sx)

# compute eigenvectors and eigenvalues of Sy, store them to vals_y, vecs_y
vals_y, vecs_y = la.eigh(Sy)

# print shape of vals_x
print(np.shape(vals_x))

# print shape of vecs_x
print(np.shape(vecs_x))

print(vals_x)
print(vecs_x)
print(vals_y)
print(vecs_y)

(2,)
(2, 2)
[-0.5  0.5]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
[-0.5  0.5]
[[-0.70710678+0.j         -0.70710678+0.j        ]
 [ 0.        +0.70710678j  0.        -0.70710678j]]


### Expectation values
Another important operation in quantum mechanics is the computation of an expectation value, which can be written as a bra-ket sandwiching an operator:

$$ \langle n | \hat{O}| m \rangle. $$

The result will depend on what $\hat{O}$ does to $|m\rangle$, and how the resulting ket projects upon $\langle n|$.

We can use the different eigenvectors from our last block as kets, and their adjoints as bras, along with the matrix form of the operators to compute these operations.  

`ket_x_0 = vecs_x[:,0]`

`bra_x_0 = ket_x_0.conj().T`

`expectation_value = np.dot(bra_x_0, np.dot(Sx, ket_x_0))`

**Question 5:** If we associate $|\chi_{\alpha}^{(x)}\rangle$ with `vec_x[:,1]`, what is the expectation value corresponding to $\langle \chi_{\alpha}^{(x)} | \hat{S}_x | \chi_{\alpha}^{(x)} \rangle $?

**Question 6:** If we associate $|\chi_{\alpha}^{(y)}\rangle$ with `vec_y[:,1]`, what is the expectation value corresponding to $\langle \chi_{\alpha}^{(y)} | \hat{S}_z | \chi_{\alpha}^{(y)} \rangle $?

In [53]:
# Compute <alpha_x|Sx|alpha_x>; print the result

# Compute <alpha_y|Sz|alpha_y>; print the result

### Commutators
We will learn later in 3141 about generalized uncertainty relations.  An important mathematical operation in formulation of uncertainty relations is the commutator, which can be taken between two operators or two matrices representing operators.  The commutator between operators $\hat{A}$ and $\hat{B}$ can be written as

$$ [\hat{A}, \hat{B}] = \hat{A} \hat{B} - \hat{B} \hat{A} $$,
and the same relation holds for the matrix form of the operators.
A few things we should note about commutators right now is:
1. If the equation above goes to zero, we say the operators commute
2. If the equation above is not zero, we say the operators do not commute
3. Commuting operators share the same set of eigenstates, and their matrix representations share the same set of eigenvectors
4. Commuting operators are related to special pairs of observables that are called compatibile observables; we can simultaneously know the value of compatible observables with unlimited precision
5. Operators that do not commute correspond to pairs of observables that are not compatible, there are strict limits on the precision with which we can simultaneously know the values of incompatible observables.

The spin operators, and their corresponding matrices, obey the following commutation relations:

$$[\hat{S}_x, \hat{S}_y] = i\hbar \hat{S}_z $$

$$[\hat{S}_y, \hat{S}_z] = i\hbar \hat{S}_x $$

$$[\hat{S}_z, \hat{S}_x] = i\hbar \hat{S}_y $$

**Question 7:** Are the observables corresponding to $\hat{S}_x$ compatible with the observables corresponding to $\hat{S}_y$?  Explain your reasoning.

**Question 8:** Confirm that the matrices $\mathbb{S}_x$, $\mathbb{S}_y$, and $\mathbb{S}_z$ obey the same commutation relations as shown above.  The syntax for computing matrix products is either `np.dot(A,B)` or equivalently `A @ B`:

`SxSy = np.dot(Sx, Sy)`

is the same as 

`SxSy = Sx @ Sy`

